[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fabric-chaincode-python"
version = "0.1.0"
description = "Hyperledger Fabric chaincode shim and contract API for Python (experimental)"
readme = "README.md"
license = {text = "Apache License v2.0"}
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.83.1",
    "grpclib>=0.4.3",
    "protobuf>=7.35.1"
]
keywords = ["Hyperledger", "Fabric", "Chaincode", "Python"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

