# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderer/clusterserver.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orderer/clusterserver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fabric_protos_python.common import common_pb2 as common_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1borderer/clusterserver.proto\x12\x07orderer\x1a\x13\x63ommon/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n\x1d\x43lusterNodeServiceStepRequest\x12\x38\n\x0fnode_conrequest\x18\x01 \x01(\x0b\x32\x1d.orderer.NodeConsensusRequestH\x00\x12@\n\x10node_tranrequest\x18\x02 \x01(\x0b\x32$.orderer.NodeTransactionOrderRequestH\x00\x12\x34\n\x10node_authrequest\x18\x03 \x01(\x0b\x32\x18.orderer.NodeAuthRequestH\x00\x42\t\n\x07payload\"g\n\x1e\x43lusterNodeServiceStepResponse\x12:\n\rtranorder_res\x18\x01 \x01(\x0b\x32!.orderer.TransactionOrderResponseH\x00\x42\t\n\x07payload\"9\n\x14NodeConsensusRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x10\n\x08metadata\x18\x02 \x01(\x0c\"]\n\x1bNodeTransactionOrderRequest\x12\x1b\n\x13last_validation_seq\x18\x01 \x01(\x04\x12!\n\x07payload\x18\x02 \x01(\x0b\x32\x10.common.Envelope\"h\n\x18TransactionOrderResponse\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\r\n\x05tx_id\x18\x02 \x01(\t\x12\x1e\n\x06status\x18\x03 \x01(\x0e\x32\x0e.common.Status\x12\x0c\n\x04info\x18\x04 \x01(\t\"\xae\x01\n\x0fNodeAuthRequest\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x66rom_id\x18\x04 \x01(\x04\x12\r\n\x05to_id\x18\x05 \x01(\x04\x12\x17\n\x0fsession_binding\x18\x06 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x07 \x01(\t2q\n\x12\x43lusterNodeService\x12[\n\x04Step\x12&.orderer.ClusterNodeServiceStepRequest\x1a\'.orderer.ClusterNodeServiceStepResponse(\x01\x30\x01\x42X\n%org.hyperledger.fabric.protos.ordererZ/github.com/hyperledger/fabric-protos-go/ordererb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderer.clusterserver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.hyperledger.fabric.protos.ordererZ/github.com/hyperledger/fabric-protos-go/orderer'
  _globals['_CLUSTERNODESERVICESTEPREQUEST']._serialized_start=95
  _globals['_CLUSTERNODESERVICESTEPREQUEST']._serialized_end=315
  _globals['_CLUSTERNODESERVICESTEPRESPONSE']._serialized_start=317
  _globals['_CLUSTERNODESERVICESTEPRESPONSE']._serialized_end=420
  _globals['_NODECONSENSUSREQUEST']._serialized_start=422
  _globals['_NODECONSENSUSREQUEST']._serialized_end=479
  _globals['_NODETRANSACTIONORDERREQUEST']._serialized_start=481
  _globals['_NODETRANSACTIONORDERREQUEST']._serialized_end=574
  _globals['_TRANSACTIONORDERRESPONSE']._serialized_start=576
  _globals['_TRANSACTIONORDERRESPONSE']._serialized_end=680
  _globals['_NODEAUTHREQUEST']._serialized_start=683
  _globals['_NODEAUTHREQUEST']._serialized_end=857
  _globals['_CLUSTERNODESERVICE']._serialized_start=859
  _globals['_CLUSTERNODESERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
