# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fabric_protos_python.orderer import cluster_pb2 as orderer_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orderer/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterStub:
    """Cluster defines communication between cluster members.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.stream_stream(
                '/orderer.Cluster/Step',
                request_serializer=orderer_dot_cluster__pb2.StepRequest.SerializeToString,
                response_deserializer=orderer_dot_cluster__pb2.StepResponse.FromString,
                _registered_method=True)


class ClusterServicer:
    """Cluster defines communication between cluster members.
    """

    def Step(self, request_iterator, context):
        """Step passes an implementation-specific message to another cluster member.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.stream_stream_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=orderer_dot_cluster__pb2.StepRequest.FromString,
                    response_serializer=orderer_dot_cluster__pb2.StepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderer.Cluster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderer.Cluster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cluster:
    """Cluster defines communication between cluster members.
    """

    @staticmethod
    def Step(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/orderer.Cluster/Step',
            orderer_dot_cluster__pb2.StepRequest.SerializeToString,
            orderer_dot_cluster__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
