# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderer/smartbft/configuration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orderer/smartbft/configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$orderer/smartbft/configuration.proto\x12\x10orderer.smartbft\"\xa9\x05\n\x07Options\x12\x1f\n\x17request_batch_max_count\x18\x01 \x01(\x04\x12\x1f\n\x17request_batch_max_bytes\x18\x02 \x01(\x04\x12\"\n\x1arequest_batch_max_interval\x18\x03 \x01(\t\x12$\n\x1cincoming_message_buffer_size\x18\x04 \x01(\x04\x12\x19\n\x11request_pool_size\x18\x05 \x01(\x04\x12\x1f\n\x17request_forward_timeout\x18\x06 \x01(\t\x12 \n\x18request_complain_timeout\x18\x07 \x01(\t\x12#\n\x1brequest_auto_remove_timeout\x18\x08 \x01(\t\x12\x19\n\x11request_max_bytes\x18\t \x01(\x04\x12#\n\x1bview_change_resend_interval\x18\n \x01(\t\x12\x1b\n\x13view_change_timeout\x18\x0b \x01(\t\x12 \n\x18leader_heartbeat_timeout\x18\x0c \x01(\t\x12\x1e\n\x16leader_heartbeat_count\x18\r \x01(\x04\x12\x17\n\x0f\x63ollect_timeout\x18\x0e \x01(\t\x12\x15\n\rsync_on_start\x18\x0f \x01(\x08\x12\x1c\n\x14speed_up_view_change\x18\x10 \x01(\x08\x12;\n\x0fleader_rotation\x18\x11 \x01(\x0e\x32\".orderer.smartbft.Options.Rotation\x12\x1c\n\x14\x64\x65\x63isions_per_leader\x18\x12 \x01(\x04\"G\n\x08Rotation\x12\x18\n\x14ROTATION_UNSPECIFIED\x10\x00\x12\x10\n\x0cROTATION_OFF\x10\x01\x12\x0f\n\x0bROTATION_ON\x10\x02\x42j\n.org.hyperledger.fabric.protos.orderer.smartbftZ8github.com/hyperledger/fabric-protos-go/orderer/smartbftb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderer.smartbft.configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.org.hyperledger.fabric.protos.orderer.smartbftZ8github.com/hyperledger/fabric-protos-go/orderer/smartbft'
  _globals['_OPTIONS']._serialized_start=59
  _globals['_OPTIONS']._serialized_end=740
  _globals['_OPTIONS_ROTATION']._serialized_start=669
  _globals['_OPTIONS_ROTATION']._serialized_end=740
# @@protoc_insertion_point(module_scope)
