# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fabric_protos_python.discovery import protocol_pb2 as discovery_dot_protocol__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in discovery/protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryStub:
    """Discovery defines a service that serves information about the fabric network
    like which peers, orderers, chaincodes, etc.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/discovery.Discovery/Discover',
                request_serializer=discovery_dot_protocol__pb2.SignedRequest.SerializeToString,
                response_deserializer=discovery_dot_protocol__pb2.Response.FromString,
                _registered_method=True)


class DiscoveryServicer:
    """Discovery defines a service that serves information about the fabric network
    like which peers, orderers, chaincodes, etc.
    """

    def Discover(self, request, context):
        """Discover receives a signed request, and returns a response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=discovery_dot_protocol__pb2.SignedRequest.FromString,
                    response_serializer=discovery_dot_protocol__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'discovery.Discovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('discovery.Discovery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Discovery:
    """Discovery defines a service that serves information about the fabric network
    like which peers, orderers, chaincodes, etc.
    """

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discovery.Discovery/Discover',
            discovery_dot_protocol__pb2.SignedRequest.SerializeToString,
            discovery_dot_protocol__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
