# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/configuration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/configuration.proto\x12\x06\x63ommon\" \n\x10HashingAlgorithm\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x19\x42lockDataHashingStructure\x12\r\n\x05width\x18\x01 \x01(\r\"%\n\x10OrdererAddresses\x12\x11\n\taddresses\x18\x01 \x03(\t\"\x87\x01\n\tConsenter\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0e\n\x06msp_id\x18\x04 \x01(\t\x12\x10\n\x08identity\x18\x05 \x01(\x0c\x12\x17\n\x0f\x63lient_tls_cert\x18\x06 \x01(\x0c\x12\x17\n\x0fserver_tls_cert\x18\x07 \x01(\x0c\"8\n\x08Orderers\x12,\n\x11\x63onsenter_mapping\x18\x01 \x03(\x0b\x32\x11.common.Consenter\"\x1a\n\nConsortium\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x95\x01\n\x0c\x43\x61pabilities\x12<\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32&.common.Capabilities.CapabilitiesEntry\x1aG\n\x11\x43\x61pabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.common.Capability:\x02\x38\x01\"\x0c\n\nCapabilityBV\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/common'
  _globals['_CAPABILITIES_CAPABILITIESENTRY']._loaded_options = None
  _globals['_CAPABILITIES_CAPABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_HASHINGALGORITHM']._serialized_start=38
  _globals['_HASHINGALGORITHM']._serialized_end=70
  _globals['_BLOCKDATAHASHINGSTRUCTURE']._serialized_start=72
  _globals['_BLOCKDATAHASHINGSTRUCTURE']._serialized_end=114
  _globals['_ORDERERADDRESSES']._serialized_start=116
  _globals['_ORDERERADDRESSES']._serialized_end=153
  _globals['_CONSENTER']._serialized_start=156
  _globals['_CONSENTER']._serialized_end=291
  _globals['_ORDERERS']._serialized_start=293
  _globals['_ORDERERS']._serialized_end=349
  _globals['_CONSORTIUM']._serialized_start=351
  _globals['_CONSORTIUM']._serialized_end=377
  _globals['_CAPABILITIES']._serialized_start=380
  _globals['_CAPABILITIES']._serialized_end=529
  _globals['_CAPABILITIES_CAPABILITIESENTRY']._serialized_start=458
  _globals['_CAPABILITIES_CAPABILITIESENTRY']._serialized_end=529
  _globals['_CAPABILITY']._serialized_start=531
  _globals['_CAPABILITY']._serialized_end=543
# @@protoc_insertion_point(module_scope)
