# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fabric_protos_python.common import common_pb2 as common_dot_common__pb2
from fabric_protos_python.peer import events_pb2 as peer_dot_events__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peer/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeliverStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deliver = channel.stream_stream(
                '/protos.Deliver/Deliver',
                request_serializer=common_dot_common__pb2.Envelope.SerializeToString,
                response_deserializer=peer_dot_events__pb2.DeliverResponse.FromString,
                _registered_method=True)
        self.DeliverFiltered = channel.stream_stream(
                '/protos.Deliver/DeliverFiltered',
                request_serializer=common_dot_common__pb2.Envelope.SerializeToString,
                response_deserializer=peer_dot_events__pb2.DeliverResponse.FromString,
                _registered_method=True)
        self.DeliverWithPrivateData = channel.stream_stream(
                '/protos.Deliver/DeliverWithPrivateData',
                request_serializer=common_dot_common__pb2.Envelope.SerializeToString,
                response_deserializer=peer_dot_events__pb2.DeliverResponse.FromString,
                _registered_method=True)


class DeliverServicer:
    """Missing associated documentation comment in .proto file."""

    def Deliver(self, request_iterator, context):
        """Deliver first requires an Envelope of type ab.DELIVER_SEEK_INFO with
        Payload data as a marshaled orderer.SeekInfo message,
        then a stream of block replies is received
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverFiltered(self, request_iterator, context):
        """DeliverFiltered first requires an Envelope of type ab.DELIVER_SEEK_INFO with
        Payload data as a marshaled orderer.SeekInfo message,
        then a stream of **filtered** block replies is received
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverWithPrivateData(self, request_iterator, context):
        """DeliverWithPrivateData first requires an Envelope of type ab.DELIVER_SEEK_INFO with
        Payload data as a marshaled orderer.SeekInfo message,
        then a stream of block and private data replies is received
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeliverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deliver': grpc.stream_stream_rpc_method_handler(
                    servicer.Deliver,
                    request_deserializer=common_dot_common__pb2.Envelope.FromString,
                    response_serializer=peer_dot_events__pb2.DeliverResponse.SerializeToString,
            ),
            'DeliverFiltered': grpc.stream_stream_rpc_method_handler(
                    servicer.DeliverFiltered,
                    request_deserializer=common_dot_common__pb2.Envelope.FromString,
                    response_serializer=peer_dot_events__pb2.DeliverResponse.SerializeToString,
            ),
            'DeliverWithPrivateData': grpc.stream_stream_rpc_method_handler(
                    servicer.DeliverWithPrivateData,
                    request_deserializer=common_dot_common__pb2.Envelope.FromString,
                    response_serializer=peer_dot_events__pb2.DeliverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Deliver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.Deliver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Deliver:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deliver(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/protos.Deliver/Deliver',
            common_dot_common__pb2.Envelope.SerializeToString,
            peer_dot_events__pb2.DeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverFiltered(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/protos.Deliver/DeliverFiltered',
            common_dot_common__pb2.Envelope.SerializeToString,
            peer_dot_events__pb2.DeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverWithPrivateData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/protos.Deliver/DeliverWithPrivateData',
            common_dot_common__pb2.Envelope.SerializeToString,
            peer_dot_events__pb2.DeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
